name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push minitwitimage
        uses: docker/build-push-action@v2
        with:
          context: src/backend
          file: src/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache,mode=max

      - name: Build and push dbimage
        uses: docker/build-push-action@v2
        with:
          context: src/db
          file: src/db/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dbimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dbimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/dbimage:webbuildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: pip install ansible
      
      - name: Install community.docker
        run: ansible-galaxy collection install community.docker

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          envkey_POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          directory: ./.github/ansible/files
          file_name: .env
          fail_on_empty: true

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy.yaml
          # Optional, directory where playbooks live
          directory: ./.github/ansible
          # Optional, SSH private key
          key: ${{secrets.SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.SSH_HOST}} ansible_user=${{secrets.SSH_USER}}


  postman:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "8945217-6624a47c-3fc2-4136-ab89-df49655d926f"
  